# Generated by Django 3.2.5 on 2021-09-02 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('environment_education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlessons',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to='persons.studentprofile'),
        ),
        migrations.AddField(
            model_name='lessonteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_teachers', to='persons.teacherprofile'),
        ),
        migrations.AddField(
            model_name='lessonclass',
            name='class_daytime',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='environment_education.classdaytime'),
        ),
        migrations.AddField(
            model_name='lessonclass',
            name='lesson_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_classes', to='environment_education.lessonteacher'),
        ),
        migrations.AlterUniqueTogether(
            name='daytime',
            unique_together={('day', 'start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='classdaytime',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='environment_education.college'),
        ),
        migrations.AddField(
            model_name='classdaytime',
            name='day_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='environment_education.daytime'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonclass',
            unique_together={('class_daytime', 'lesson_teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='classdaytime',
            unique_together={('college', 'class_num', 'day_time')},
        ),
    ]
