# Generated by Django 3.2.5 on 2021-09-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='user',
            new_name='std_user',
        ),
    ]
