# Generated by Django 3.2.5 on 2021-09-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_rename_user_studentprofile_std_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='std_user',
            new_name='user',
        ),
    ]
